Struct Editor: Implement javascript editor framework
celements/celements-structuredDataEditor pull request #15
Opened 2017-06-08 20:16 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-426

2017-06-11 17:43 UTC, fpichler commented
@ebeutler, @dkhasham  refoactoring is finished. Please review this PR.

2017-06-16 10:00 UTC, ebeutler requested changes

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/resources/structEditJS/StructEditor.js
> +**/
empty comment. Either add comment or remove.

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/resources/structEditJS/StructEditor.js
> +  if(typeof window.CELEMENTS.Utils=="undefined"){window.CELEMENTS.Utils={};};
structEdit lower case, Utils upper case -> do we (or should we?) have come naming conventions for these?

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/resources/structEditJS/StructEditor.js
> +      //TODO add possibility to add JS-listener which can do additional 'isDirty' checks
Is there an issue for this? If so, please link in comment

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/resources/structEditJS/StructEditor.js
> +      //TODO add possibility to add JS-listener which can execute alternative save actions
Is there an issue for this? If so, please link in comment

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/resources/structEditJS/StructEditor.js
> +  //            var formId = response.key;
needed as comment?

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/resources/structEditJS/StructEditor.js
> +//        return tinyMCE.get(fieldElem.id).isDirty();
Is there an issue for this? If so, please link in comment

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/resources/structEditJS/StructEditor.js
> +        _me._saveAndContinueAjax(formId, {
Either use onComplete and handle problems or add onFailed(?) ... otherwiese e.b. Velocity-Exceptions could lead to wrong behaviours

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/resources/structEditJS/StructEditor.js
> +})(window);
missing empty line as EOF

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/resources/structEditJS/initStructEditor.js
> +})(window);
missing empty line as EOF

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/templates/celAjax/Messages.vm
> +$jsonBuilder.getJSON()
missing empty line as EOF

2017-06-16 10:00 UTC, ebeutler commented on web-module/src/main/webapp/templates/celMacros/StructEditorMessages.vm
> +$jsonBuilder.closeDictionary()
missing empty line as EOF

2017-06-17 17:29 UTC, fpichler commented
can you please re-review?

2017-06-20 11:46 UTC, ebeutler approved these changes

2017-06-20 15:10 UTC, merged