cel-input-date-time optional time
celements/celements-structuredDataEditor pull request #158
Opened 2022-03-21 14:06 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-1017

2022-03-23 04:36 UTC, fpichler requested changes

2022-03-23 04:36 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> -        const timeValue = dateTimeValues[1] || "00:00";
You drop the default behaviour on an empty field. Opening a new progonEvent in the editor in both time fields already 00:00 is entered to help filling out the fields. Please readd this default behaviour.

2022-03-23 04:36 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +        console.debug("_updateVisibleFromHidden date", _me._dateTimeComponent, dateValue);
Please move this logging into else block and readd the dateValue to the available logging in the if clause. The log is already very verbose and this is increasing this issue.

2022-03-23 04:36 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +        cssFiles.forEach((cssFile) => {
better use for-of loop
```
for (variable of iterable) {
  // code block to be executed
}
```

2022-03-23 04:36 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +            this.datePart.setAttribute('placeholder', newValue);
I think a break is missing here. Otherwise changing a placeholder-date always changes placeholder-time too.

2022-03-23 04:36 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +        this.#datePickerIcon = this.#datePickerIcon ?? new Element('i', {
refactoring this part please replace the prototypjs 'new Element' with document.createElement too?

2022-03-23 09:45 UTC, msladek commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +        console.debug("_updateVisibleFromHidden date", _me._dateTimeComponent, dateValue);
we should consider using a logging framework

2022-03-23 09:48 UTC, msladek commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> -        const timeValue = dateTimeValues[1] || "00:00";
readding 00:00 into the input field defeats the purpose of having a default value for the time picker

2022-03-23 13:25 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> -        const timeValue = dateTimeValues[1] || "00:00";
well, I don't think, that this defeats the default behavior. My request is "Please readd this default behavior." To me this looks like you should add the default value of "00:00" in the event-editor to fix the regression issue.

2022-03-23 13:29 UTC, fpichler requested changes
Please fix the mentioned regression issue about the default time value

2022-04-08 07:56 UTC, msladek commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> -        const timeValue = dateTimeValues[1] || "00:00";
default date/time will be dealt with in a separate issue

2022-04-08 07:56 UTC, msladek commented
default date/time will be dealt with in a separate issue

2022-04-10 16:41 UTC, fpichler approved these changes

2022-04-10 23:03 UTC, merged