cel-input-date-time min/max
celements/celements-structuredDataEditor pull request #161
Opened 2022-04-24 00:19 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-1030

2022-04-26 16:09 UTC, fpichler requested changes

2022-04-26 16:09 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +      const onChangedBind = this.#onChanged.bind(this);
This breaks 'only Once' idempotency, because `stopObserving` needs equality of function.  Yet, each `bind` call is generating a new function object. Thus `stopObserving` will fail to unsubscribe correctly.

2022-04-26 16:09 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +        const openPickerBind = this.openPicker.bind(this);
This breaks 'only Once' idempotency, because `stopObserving` needs equality of function.  Yet, each `bind` call is generating a new function object. Thus `stopObserving` will fail to unsubscribe correctly.

2022-04-26 16:09 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +        this.#inputTimeField.celObserve(EVENT_FIELD_CHANGED, this.#onDateTimeChange.bind(this));
Removing `celStopObserving` breaks 'only Once' idempotency if `initTimeField` is executed multiple times.

2022-04-29 09:00 UTC, fpichler requested changes

2022-04-29 09:00 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +    initField(buttonCssSelector) {
why is initField a public method? Would it not be better to make it private?

2022-04-29 09:00 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +        if (data.min && data.min > date) {
easier to read:
```suggestion
        if (data.min && (data.min > date)) {

```

2022-04-29 09:00 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +        } else if (data.max && data.max < date) {
easier to read:
```suggestion
        } else if (data.max && (data.max < date)) {

```

2022-04-29 09:00 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +    setPickerConfig(config) {
setter can be used
```suggestion
    set pickerConfig(config) {

```

2022-04-29 09:00 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
>    class CelementsDateTimePickerFactory {
please change this class to "static". Overwrite the constructor with an exception throw that the class is static.
e.g. [constructor of static class](https://medium.com/@fab1o/javascript-static-class-3e1acdaec81)
Make all public methods static.
[mdn docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#static_methods_and_properties)

2022-04-29 14:11 UTC, fpichler requested changes

2022-04-29 14:11 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
>      initFields() {
why is initField a public method? Would it not be better to make it private?

2022-04-29 14:11 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
> +        return [];
Should we log the exception at least on debug level?

2022-04-29 14:23 UTC, msladek commented on web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js
>      initFields() {
because it is called extenally: https://github.com/celements/celements-structuredDataEditor/blob/b305c096f2c9a7ebbbd811a78dc708c6be17fb92/web-module/src/main/webapp/resources/structEditJS/dateTime/celements-date-time-field.js#L450

2022-04-30 19:00 UTC, fpichler approved these changes

2022-05-01 19:44 UTC, merged