StructuredDataEditorService remove fallback to first object
celements/celements-structuredDataEditor pull request #20
Opened 2017-11-23 13:08 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-575

2017-11-26 12:48 UTC, fpichler requested changes
We discussed the missing newObject call, yet I agree that we should try to taggle this issue with an 'Optional' inside java. If we get NPEs because of null 'value' or similar we need to look for an appropriate solution then.

2017-11-26 12:48 UTC, fpichler commented on component/src/main/java/com/celements/structEditor/DefaultStructuredDataEditorService.java
> +  Optional<BaseObject> getRequestXObjectInStructEditor(XWikiDocument cellDoc, XWikiDocument onDoc) {
please make it a 'private' method or if it is a service method add it to the Role interface

2017-11-26 12:48 UTC, fpichler commented on component/src/main/java/com/celements/structEditor/DefaultStructuredDataEditorService.java
> +  Optional<BaseObject> getXObjectInStructEditor(XWikiDocument cellDoc, XWikiDocument onDoc,
please make it a 'private' method or if it is a service method add it to the Role interface

2017-12-06 17:10 UTC, dkhasham approved these changes

2017-12-07 04:46 UTC, fpichler approved these changes

2017-12-08 12:51 UTC, merged