add script redirectToNextDocRef to be able create new users
celements/celements-structuredDataEditor pull request #211
Opened 2023-06-30 07:35 UTC by cbspichler

https://synjira.atlassian.net/browse/CELDEV-1129

2023-07-06 13:56 UTC, msladek approved these changes, later dismissed

2023-07-08 15:33 UTC, fpichler requested changes

2023-07-08 15:33 UTC, fpichler commented on web-module/src/main/webapp/templates/celAjax/redirectToNextDocRef.vm
> +  #set($spaceRef = $services.reference.create().space($pageType).build())
The space may not be influencable by the user. This has security implications. The system must only accept users of a restricted space (so far this is the XWiki-space). We further should think about expecting "register" rights for creating documents in the XWiki space. Yet, this is a topic of an other issue.
Please change the logic, that the space cannot be influenced by request-parameters.

2023-08-02 21:43 UTC, fpichler approved these changes

2023-08-03 06:20 UTC, merged