new structfieldtype for selectTagAutocomplete
celements/celements-structuredDataEditor pull request #22
Opened 2018-01-29 17:09 UTC by dkhasham

https://synjira.atlassian.net/browse/PROGON-706

2018-02-05 05:22 UTC, fpichler submitted a review, later dismissed

2018-02-05 15:07 UTC, fpichler requested changes

2018-02-05 15:07 UTC, fpichler commented on component/src/main/java/com/celements/structEditor/DefaultStructuredDataEditorService.java
> +  public List<String> getSelectTagAutocompleteJsPath() {
The result is a list. Therefore please use ...Paths or ...PathList as method name

2018-02-05 17:46 UTC, fpichler submitted a review, later dismissed

2018-02-05 20:18 UTC, msladek requested changes

2018-02-05 20:18 UTC, msladek commented on component/src/main/java/com/celements/structEditor/fields/SelectTagAutocompletePageType.java
> +      if ((multiselect.size() > 0) && multiselect.iterator().next()) {
simpler: `boolean multiselect = objIter.transform(...).first().or(false);`

2018-02-05 20:18 UTC, msladek commented on component/src/main/java/com/celements/structEditor/fields/SelectTagAutocompletePageType.java
> +      if ((separator.size() > 0)) {
simpler: `Optional<String> separator = objIter.transform(...).first();`

2018-02-05 20:18 UTC, msladek commented on component/src/main/java/com/celements/structEditor/fields/SelectTagAutocompletePageType.java
> +      if (types.size() > 0) {
simpler: `Optional<SelectAutocompleteRole> type = objIter.transformAndConcat(...).first();`

2018-02-05 20:18 UTC, msladek commented on component/src/main/java/com/celements/structEditor/fields/SelectTagAutocompletePageType.java
> +      LOGGER.error("cell doesn't exist '{}'", cellDocRef, exc);
`warn` seems more appropriate

2018-02-05 20:18 UTC, msladek commented on component/src/main/java/com/celements/structEditor/fields/SelectTagAutocompletePageType.java
> +          selectTagAutocomplete).iter().transformAndConcat(new FieldGetterFunction<>(
extract local variable `FluentIterable<BaseObject> objIter = XWikiObjectFetcher.on(cellDoc).filter(selectTagAutocomplete).iter();`

2018-02-05 20:18 UTC, msladek commented on web-module/src/main/webapp/templates/celTemplates/SelectTagAutocompleteView.vm
> +  <!-- WARN SelectTagView: doesn't support display type: $!propClass.get().getProperty('displayType').getValue() -->
this is not the SelectTagView

2018-02-05 20:18 UTC, msladek commented on component/src/main/java/com/celements/structEditor/classes/SelectTagAutocompleteEditorClass.java
> +  public static final String CLASS_DEF_HINT = SPACE_NAME + "." + DOC_NAME;
add `public static final String CLASS_FN = SPACE_NAME + "." + DOC_NAME;` which has be used by the field builders.
the CLASS_DEF_HINT is the same as our full name.

2018-02-06 12:15 UTC, msladek requested changes

2018-02-06 12:15 UTC, msladek commented on web-module/src/main/webapp/templates/celTemplates/SelectTagAutocompleteView.vm
> +  <!-- WARN SelectTagutocompleteView: doesn't support display type: $!propClass.get().getProperty('displayType').getValue() -->
typo

2018-02-06 12:15 UTC, msladek commented on component/src/main/java/com/celements/structEditor/classes/SelectTagAutocompleteEditorClass.java
>        CLASS_DEF_HINT, "select_tag_autocomplete_separator").prettyName("Separator").build();
please use CLASS_FN for field builders. This can be replaced in the future by a ClassReference

2018-02-06 17:54 UTC, msladek approved these changes

2018-02-07 13:14 UTC, merged