NumberTag & StructObjectListEdit.js
celements/celements-structuredDataEditor pull request #85
Opened 2020-01-31 02:45 UTC by msladek

2020-01-31 08:19 UTC, fpichler requested changes

2020-01-31 08:19 UTC, fpichler commented on component/src/main/java/com/celements/structEditor/fields/NumberTagPageType.java
> +  public void collectAttributes(AttributeBuilder attrBuilder, DocumentReference cellDocRef) {
unit tests missing

2020-01-31 08:19 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/StructObjectListEdit.js
> +  $j(document).ready(observeCreateObject);
struct editor forms may be loaded async. Thus please register additionally on 'celements:contentChanged'.

2020-01-31 08:19 UTC, fpichler commented on web-module/src/main/webapp/resources/structEditJS/StructObjectListEdit.js
> +(function(window, undefined) {
please refactor to a js-class

2020-02-01 22:08 UTC, msladek commented on web-module/src/main/webapp/resources/structEditJS/StructObjectListEdit.js
> +(function(window, undefined) {
CELDEV-865

2020-02-03 10:56 UTC, fpichler approved these changes

2020-02-03 12:04 UTC, merged